SHAYARI = (
  "Har Tanha Raat Mein Ek Naam Yaad Aata Hai Kabhi Subhah To Kabhi Shaam Yaad Aata Hai,Jab Sochte Hain Kar Lein Dobara Mohabbat,Fir Pehli Mohabbat Ka Anzaam Yaad Aata Hai.",
  "Humein Shayar Samajh Ke Yoon Najar Andaz Mat Kariye,Najar Hum Fer Le To Husn Ka Baazar Gir Jayega.",
  "Humari Haisiyat Ka Andaza Tum Ye Jaan Ke Laga Lo,Hum Kabhi Unke Nahi Hote Jo Har Kisi Ke Ho Gaye.",
  "Iss Se Zyada Tujhe Aur Kitna Qareeb Laaun Main,Ki Tujhe Dil Mein Rakh Kar Bhi Mera Dil Nahi Bharta.",
  "Ye Zindagi Hasin Hai Iss Se Pyar Karo,Abhi Hai Raat To Subah Ka Intezar Karo,Wo Pal Bhi Ayega Jiski Khwahish Hai Aapko,Rab Par Rakho Bharosa Waqt Par Aitbar Karo.",
  "Hausle Bhi Kisi Hakeem Se Kam Nahi Hote,Har Takleef Mein Takat Ki Davaa Dete Hain.",
  "Ek Sooraj Tha Ki Taaro Ke Gharane Se Uthha,Aankh Hairan Hai Kya Shakhs Zamane Se Uthha.",
  "Kaam Karo Aisa Ki Ek Pehchaan Ban Jaye,har Kadam Aisa Chalo Ki Nishan Ban Jaye,Yehan Zindagi To Har Koi Kaat Leta Hai,Zindagi Jiyo Iss Kadar Ki Misaal Ban Jaye.",
  "Bade Hi Ajeeb Hain Ye Zindagi Ke Raaste,Anjane Mod Par Kuchh Log Apne Ban Jate Hain,Milne Ki Khushi Dein Ya Na Dein,Magar Bichadne Ka Gam Zaroor De Jate Hain.",
  "Zindagi Sirf Mohabbat Nahi Kuchh Aur Bhi Hai,Zulf-o-Rukhsaar Ki Jannat Nahi Kuchh Aur Bhi Hai,Bhookh Aur Pyaas Ki Maari Huyi Iss Duniya Mein,Ishq Hi Ek Hakiqat Nahi Kuchh Aur Bhi Hai.",
  "Har Tanha Raat Mein Ek Naam Yaad Aata Hai,Kabhi Subhah To Kabhi Shaam Yaad Aata Hai,Jab Sochte Hain Kar Lein Dobara Mohabbat,Fir Pehli Mohabbat Ka Anzaam Yaad Aata Hai.",
  "Chal Mere Hum-Nashin Ab Kahin Aur Chal,Iss Chaman Mein Ab Apna Gujaara Nahi,Baat Hoti Gulon Tak To Seh Lete Hum,Ab To Kaanton Pe Bhi Haq Humara Nahi.",
  "Sirf Chehre Ki Udaasi SeBhar Aaye Teri Aankhon Mein Aansoo,Mere Dil Ka Kya Aalam Hai Ye To Tu Abhi Jaanta Nahi.",
  "Kabhi Lafz Bhool Jaaun Kabhi Baat Bhool Jaaun,Tujhe Iss Kadar Chahun Ki Apni Jaat Bhool Jaaun,Kabhi Uthh Ke Tere Paas Se Jo Main Chal Dun,Jaate Huye Khud Ko Tere Paas Bhool Jaaun.",
  "Alfaz Ki Shakl Mein Ehsaas Likha Jata Hai,Yahan Par Paani Ko Pyaas Likha Jata Hai,Mere Jazbat Se Wakif Hai Meri Kalam Bhi,Pyar Likhu To Tera Naam Likha Jata Hai.",
  "Tum Nahi Hote Ho To Bahut Khalta Hai,Pyar Kitna Hai Tumse Pata Chalta Hai.",
  "Mere Dushman Bhi Mere Mureed Hain Shayad,Waqt-BeWaqt Mera Naam Liya Karte Hain,Meri Gali Se Gujarte Hain Chhupa Ke Khanzar,Ru-Ba-Ru Hone Par Salaam Kiya Karte Hain.",
  "Meri Takdeer Mein Jalna Hai To Jal Jaunga,Main Koi Tera Vada To Nahi Jo Badal Jaunga,MujhKo Na Samjhaao Meri Zindagi Ke Usool,Main Khud Hi Thhokar Kha Ke Sambhal Jaunga.",
  "Tera Pyar Paane Ke LiyeMaine Kitna Intezar Kiya,Aur Uss Intezar Mein Na Jaane,Kitno Se Pyar Kiya.",
)
